# SumOfFibonnaciEvenNumber

Prob. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sol.

class FibonnaciNumber

  def initialize(max)
    @num1 = 0
    @num2 = 1
    @max = max
    @i = 0
    @sum = 0
  end

  def even_fibonnaci
    while(@i < @max)
      @i = @num1 + @num2
      @sum += @i if @i % 2 == 0
      @num1 = @num2
      @num2 = @i 
    end
    @sum
  end
end

result = FibonnaciNumber.new(4000000)
p result.even_fibonnaci
